version: '3.1'

services:
  php:
    build:
      context: .
      dockerfile: ./php72/Dockerfile
    ports:
      - 8072:80
      # - {porta-local}:{portaContainer}
    volumes:
      - ../src:/var/www/html
      # - ../pastaLocal : /var/www/html

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senharoot
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
